name: Norway
favicon: null
layout_spectrum: 0.5043415911495686
typography_spectrum: 0.7832761439494789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7266180128790438
  lightness: 0.5314188795164227
  saturation: 0.800914263818413
  rhythmicContrast: 0.054549690335989
purpose: []
